### ISSUE TITLE
SwiftLint path in Preferences is always prepopulated which can lead to confusion

### ISSUE THREAD

**Issue by TatyanaShabaeva** [bealex/SwiftLintAppCode#10]
Similar to https://github.com/bealex/SwiftLintAppCode/issues/11

Repro:
* install _swiftlint_ (e.g. via _brew_)
* install SwiftLint plugin for AppCode
* open AppCode Preferences | SwiftLint configuration -> SwiftLint path is prepopulated with the installation directory
* clear SwiftLint path
* hit "OK" or "Apply", close Preferences
* modify Swift code, verify that SwiftLint inspections do not work
* open Preferences -> SwiftLint path is prepopulated again
* do not hit "OK" or "Apply", just close Preferences
* modify Swift code -> surprisingly, SwiftLint inspections are back again.

I'd expect SwiftLint path to be prepopulated when plugin is just installed. When user removes the value manually there is no need to prepopulate the path.

**Comment by bealex** [comment]
Thanks! Should be fixed in 1.6

**Comment by TatyanaShabaeva** [comment]
Thanks. Checked with v1.6, works.
