### ISSUE TITLE
Disabled "Autocorrect" option gets enabled each time Preferences are opened

### ISSUE THREAD

**Issue by TatyanaShabaeva** [bealex/SwiftLintAppCode#11]
Similar to https://github.com/bealex/SwiftLintAppCode/issues/10

Repro:
* open AppCode Preferences | SwiftLint configuration
* disable "Autocorrect quick-fix"
* hit "OK" or "Apply", close Preferences
* modify Swift code, verify that quick-fixes are disabled
* open Preferences -> "Autocorrect quick-fix" option is enabled again

**Comment by bealex** [comment]
Thanks! Should be fixed in 1.6

**Comment by TatyanaShabaeva** [comment]
Thanks. Checked with v1.6, works.
