### ISSUE TITLE
'Enable "Autocorrect" quick-fix' option controls not only quick-fix but the inspection itself

### ISSUE THREAD

**Issue by TatyanaShabaeva** [bealex/SwiftLintAppCode#12]
Repro:

* open AppCode Preferences | SwiftLint configuration
* disable "Autocorrect quick-fix", hit "OK", close Preferences
* open Swift file with some badly styled code
* run Swiftlint inspection against the file

Actual: "No suspicious code found". Looks like 'Enable "Autocorrect" quick-fix' option is responsible for enabling/disabling Swiftlint inspection.

Expected: I'd expect to have Swiftlint inspection enabled in such case, only quick-fixes in editor should be disabled.

**Comment by bealex** [comment]
Fixed in 1.7
