### ISSUE TITLE
Changes made with "Autocorrect" quick-fix cannot be undone

### ISSUE THREAD

**Issue by TatyanaShabaeva** [bealex/SwiftLintAppCode#13]
Repro:

* open AppCode Preferences | SwiftLint configuration
* enable "Autocorrect quick-fix", hit "OK", close Preferences
* open Swift file with some badly styled code
* invoke Alt+Enter -> "Autocorrect"
* hit Cmd+Z

Actual: "Cannot Undo: following files have changed that cannot be undone" dialog.

Expected: changes made with "autocorrect" should be undone.

**Comment by bealex** [comment]
Thanks for the report. But it may be impossible to do that, because quick-fix is being done with terminal command and can be applied only to the whole file at once.

I'll check what can be done though.

**Comment by bealex** [comment]
Will be partially fixed in 1.7. I believe the nature of quick-fix does not allow to fix it completely.
