### ISSUE TITLE
When does the plugin re-process the config file?

### ISSUE THREAD

**Issue by reitzig** [bealex/SwiftLintAppCode#16]
It is not clear to me when the plugin processes changes to `.swiftlint.yml`.

I just added

~~~yml
disabled_rules:
  - todo
~~~

but not even an IDE restart makes the warning go away. Changes to the file should take effect immediately!

(I *think* that activating SwiftLint in the first place took an update of the plugin to take effect, so maybe then?)

**Comment by bealex** [comment]
Plugin does not use `.swiftlint.yml` at all. It looks for its presence, nothing more.

SwiftLint itself rereads configuration every time it is run. So, basically, it should take effect after next inspection cycle (usually after changing a char in the file)

**Comment by reitzig** [comment]
I see. Maybe I didn't actually change any files before. I *would* expect changed settings to trigger a re-run, though.

**Comment by bealex** [comment]
AppCode triggers inspections when it thinks that it is a good time to do. Plugin does not decide it. Generally it works OK.

**Comment by reitzig** [comment]
Huh, I see. Can we tell AppCode to watch `.swiftlint.yml` for changes (as it does source and other config files)?

Maybe: https://www.jetbrains.com/help/idea/2016.3/using-file-watchers.html

**Comment by bealex** [comment]
I will look into it.

**Comment by bealex** [comment]
Should be fixed in 1.10.3
