### ISSUE TITLE
Create one config entry per inspection

### ISSUE THREAD

**Issue by reitzig** [bealex/SwiftLintAppCode#17]
Currently, AppCode's inspection configuration has only one entry for SwiftLint that covers all the inspections. I would like to have some of its warning be weak, others normal warnings.

Please create one entry per provided inspection.

(This could also make parts of the YML config obsolete, as turning inspections on and off would be configured in the settings then.)

**Comment by bealex** [comment]
I like it and will think about it. But.

You should be able to configure SwiftLint once and use it in Xcode, with CI, with AppCode. This is a big deal, and I can not get rid of `.swiftlint.yml` because of that.

So plugin should be able to parse config file and update checkboxes accordingly (and vice versa). That is not something I want to do right now.

**Comment by reitzig** [comment]
I realize that this might be a lot of work. While some parts (e.g. the `localInspection` tags in the Manifest) could be generated by scripts from `swiftline rules`, there does not seem an easy way to lint single rules, and the output of SwiftLint is not very nice.

FWIW: realm/SwiftLint/issues/1305

(I wonder if Tailor and/or Taylor are better suited for interfacing with IDEs?)

> You should be able to configure SwiftLint once and use it in Xcode, with CI, with AppCode. This is a big deal, and I can not get rid of .swiftlint.yml because of that.
>
> So plugin should be able to parse config file and update checkboxes accordingly (and vice versa). That is not something I want to do right now.

One could argue that decisions *how* to display the warnings are IDE-specific. For instance, do others have as many categories as AppCode? That is, the settings under Inspections could be left AppCode-specific (except maybe turning inspections on and off altogether).

Settings from the main references (as proposed in #20) would have to be made persistent in the config file, yes.

**Comment by bealex** [comment]
I will look into it. Not right now, but I will.

**Comment by bealex** [comment]
That appears as too much effort for a small benefit. Configuration file is much more powerful. Closing for now, maybe will implement in some distant future.
