### ISSUE TITLE
Provide interface to config file from AppCode preferences

### ISSUE THREAD

**Issue by reitzig** [bealex/SwiftLintAppCode#20]
Manually creating and maintaining `.swiftlint.yml` is not nice, in particular because the documentation of that tool is ... suboptimal.

The plugin could alleviate this by providing GUI for at least the most relevant settings and generating the config file (and triggering reruns, cf. #16). Advanced users could still work on the file directly.

**Comment by yeswolf** [comment]
I'd -1 this one, cause a) less wizards, more value b) wizards are hard to mantain + require immediate attention when something significantly changes c) YML could be edited in AppCode with highlighting and so on.

**Comment by bealex** [comment]
Will close this one for now. I tried to implement something like that, but it will require lots and lots of work and support (SwiftLint is being developed and updated pretty fast) and I do not think I can update plugin as fast.

And I agree with @yeswolf.
