### ISSUE TITLE
SwiftLint inspections do not work unless a change to plugin settings is made

### ISSUE THREAD

**Issue by TatyanaShabaeva** [bealex/SwiftLintAppCode#23]
Plugin version 1.7.

Repro:
* install plugin
* open Swift file -> no SwiftLint inspections
* go to Preferences | SwiftLint Configuration, disable "Enable 'Autocorrect' quick-fix", then enable it back, hit Apply, close Preferences
* open Swift file -> SwiftLint inspections are in place

**Comment by gmosx** [comment]
Ah, fantastic, thanks for the tip!
It was driving me crazy that the plugin didn't work with AppCode!

**Comment by bealex** [comment]
Should be fixed in 1.8. :)
