### ISSUE TITLE
Enabled Inspection makes typing significantly laggy

### ISSUE THREAD

**Issue by mekarthedev** [bealex/SwiftLintAppCode#25]
Automatic Inspection allows getting lint feedback as you type. But when SwiftLint's inspection is enabled typing becomes annoyingly laggy.

See attached [screen recording](https://github.com/bealex/SwiftLintAppCode/files/1180444/swiftlint-laggy-720p.mov.zip).

SwiftLint plugin v1.8, AppCode 2017.2 (172.3317.89), MacBook Pro 2015, macOS 10.12.5, Xcode 8.2.1, 30/12 kloc of mixed Swift/ObjC code + CocoaPods.

**Comment by bealex** [comment]
Will look into it. Was it the same with previous versions of AppCode?

**Comment by mekarthedev** [comment]
Can't say that. I've tried the plugin the first time just after upgrading to 2017.2.

**Comment by bealex** [comment]
Got it! Thanks for the report.

**Comment by bealex** [comment]
Should be fixed. Can you verify that? Thanks!

**Comment by mekarthedev** [comment]
Can't see any lagging now. Thanks for fixing!
