### ISSUE TITLE
.swiftlint.yml is ignored with SwiftLint v0.22.0

### ISSUE THREAD

**Issue by sebkasanzew** [bealex/SwiftLintAppCode#27]
After updating to SwiftLint v0.22.0 the plugin uses the default swiftlint settings for checking the code and ignores the .swiftlint.yml file. Switching back to SwiftLint v0.21.0 solves the issue.

I'm using AppCode 2017.2

**Comment by sebkasanzew** [comment]
After further investigation this is caused by these changes: [realm/SwiftLint#1748](https://github.com/realm/SwiftLint/pull/1748)

I guess this plugin needs to add support for the new `--config-defaults` and `--config-overrides` options, because the old `--config` is obsolete and seems to work in a different way now.

**Comment by bealex** [comment]
Thanks! Right now I'm testing new version of the plugin myself, it should be ready in several days.

**Comment by sebkasanzew** [comment]
Any update on this?

**Comment by bealex** [comment]
I've uploaded the update. Please check it (it should go live in a day or two). If something will still be missing, file the bugs.
