### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by kaizimmer** [bealex/SwiftLintAppCode#28]
Hi Alex,

first of all I'd like to thank you for this plugin.
It would be nice if it would be possible to configure the path to the .swiftlint.yml (just like one can do with the swiftlint binary path)

Kind regards

**Comment by bealex** [comment]
Hi,

Thanks :)

I try to find config file to use in the project. It should be there because I want same behavior for command line swiftlint and the plugin.

Can you describe the case of having another config file?

**Comment by vladimir-bebeshko** [comment]
> Can you describe the case of having another config file?

The case is very simple: when we work not with a project, but with a workspace, we want the same set of rules to be applied to all the projects in the workspace. So, we have the .swiftlint.yml file not in the project root, but in the workspace root.

 The command-line swiftlint works well in this case, as it looks for the .swiftlint.yml at the parent directory when it doesn't find it in the current one, and so on. 

The fastlane has the ability to set path to the .yml-file, so the consistency with CI/CD tools would be nice too.

**Comment by bealex** [comment]
v 1.11.0 can be better for this, can you please check it?
