### ISSUE TITLE
Error: IOException: Stream closed

### ISSUE THREAD

**Issue by gwsounddsg** [bealex/SwiftLintAppCode#29]
AppCode version: 2017.2.4
Xcode version: 8.3.3
Swiftlint version: 0.23.1
Swiftlint Pluging version: 1.9.1

Issue:
While using AppCode I keep getting errors in the event log reading: "Error: IOException: Stream closed". I haven't been able to identify exactly what I am doing to cause this error to pop up, but it happens multiple times while I'm writing code. In a ten minute span of typing I'll get it 20+ times.

I disabled this plugin and the errors stopped. The linter appears to be behaving correctly and there are no errors if I just run the same project on Xcode. It also started appearing only after I upgraded to AppCode v2017.2.4.

![ioexception](https://user-images.githubusercontent.com/1510334/31854636-214a7518-b662-11e7-8533-ed28ff470e1c.jpeg)

**Comment by bealex** [comment]
Hi,

Can you please check that you are using the latest build of the plugin?

**Comment by gwsounddsg** [comment]
Yes, as my issue states at the top what all my version numbers are. For this plugin I am running v1.9.1.

**Comment by bealex** [comment]
Thanks!
Is path to swiftlint executable in AppCode settings correct?

I get this error myself, but it happens extremely rarely (once in couple of weeks or even less than that) when something exceptional is done with the swift file (like it disappears via git checkout).

I will try to reproduce this, but more information (exact code or action when this happens) will be very helpful.

**Comment by gwsounddsg** [comment]
Currently the path is: `/usr/local/bin/swiftlint'.` Is this the correct place if I have a local yml file for the project?

**Comment by bealex** [comment]
This is the correct path if you've installed SwiftLint via HomeBrew.

Thanks! Will try to reproduce.

**Comment by gwsounddsg** [comment]
Update:

With the 2017.2.5 update I am no longer getting this error. Super odd.

**Comment by gwsounddsg** [comment]
Woops, disregard my last comment. The update disabled showing the errors but they're still there.

**Comment by svdo** [comment]
I have this problem too. I'm using latest AppCode EAP. In the end it even causes AppCode to break down, because it runs out of available file descriptors...

AppCode: 2017.3 EAP Build #OC-173.3415.31, built on October 26, 2017
Xcode: 9.0.1
SwiftLint: 0.21.0
SwiftLint plugin version: 1.9.1

**Comment by svdo** [comment]
Just now I also got `Error: IOException: Bad file descriptor`.

**Comment by svdo** [comment]
The problem seems to occur when I *save* the file.

**Comment by bealex** [comment]
You mean "Cmd+S"? AFAIK, it does nothing in AppCode (and all IJ products). Anyway, your comment gave me an idea, thanks!

**Comment by gwsounddsg** [comment]
Just an update:

I was still getting this error when I was using Xcode 9. But with the release of AppCode 2017.3 it has stopped.

**Comment by bealex** [comment]
Thanks for the update. Anyway, 1.10 is out with some major updates in plugin structure. Should work better now.
