### ISSUE TITLE
Passing file over stdin breaks nested configs and include/exclude functionality

### ISSUE THREAD

**Issue by brennantaylor** [bealex/SwiftLintAppCode#31]
In our `.swiftlint.yml` we have some include/exlcudes that also have directory names in them. When passing the file through stdin swiftlint doesn't know the path to it and some functionality doesn't work.

**Comment by danl3v** [comment]
+1 to this

**Comment by bealex** [comment]
This will be in the next update.

**Comment by danl3v** [comment]
Great thanks! Really enjoying the plugin

**Comment by bealex** [comment]
I've submitted the update to JB. Should be out in couple of days.

Please check if it works as you want it to and feel free to tell me if something is wrong.
