### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by wsof401** [bealex/SwiftLintAppCode#35]
This is my .swiftlint.yml declared

```
excluded:
  - Pods
  - R.generated.swift 
  - PXN/API.swift
opt_in_rules:
  - empty_count
  - first-where
  - force-unwrapping
  - implicit-return
  - joined-default-parameter
  - variable-declaration-whitespace
  - literal-expression-end-indentation
  - pattern-matching-keywords
  - private-actions
  - strict-fileprivate
  - vertical-parameter-alignment-on-call
line_length: 140

```

this is the error when I build in appCode
![image](https://user-images.githubusercontent.com/3211941/39235094-8f1bd2b2-48a7-11e8-854c-89586a7bc55f.png)

xcode version : 9.3
appCode version: 2018.1.1
plugin version :  1.10.3

**Comment by bealex** [comment]
Please replace dashes "-" with underscores "_".

**Comment by wsof401** [comment]
the `private_action` is still error
![image](https://user-images.githubusercontent.com/3211941/39251987-395b8aea-48d7-11e8-8927-da3cc7c7427d.png)

**Comment by bealex** [comment]
These are not SwiftLint plugin errors, they are errors of SwiftLint itself. Here is about this error, as far as I understand.

https://github.com/realm/SwiftLint/issues/1997
