### ISSUE TITLE
Autocorrect don't work.

### ISSUE THREAD

**Issue by bimawa** [bealex/SwiftLintAppCode#36]
Tried quick-fix:
1. <kbd>OPT+Enter</kbd>
2. <kbd>Enter</kbd>
3. Exception: 

```
09:36   Error
        Can't quick-fix.
        Exception: null
```

plugin version: 1.10.3
swiftLint: 0.27.0

**Comment by bealex** [comment]
Can you please look into log files, there should be an exception itself. It will be very helpful. Thanks!

**Comment by bimawa** [comment]
[idea.log](https://github.com/bealex/SwiftLintAppCode/files/2565579/idea.log)
Yes, here it is
