### ISSUE TITLE
Error: SwiftLint takes too long to process

### ISSUE THREAD

**Issue by jgarciatt** [bealex/SwiftLintAppCode#37]
I'm using AppCode and the SwiftLint plugin, and since a couple of weeks ago I started to get **Error: SwiftLint takes too long to process** file every time I edit a file. I had to disable the plugin in order to be able to work, because it reached a point where the cursor was delayed to show the error in the event log. This happens with every class, no matter the size, even a file of 20 lines of code cause the error. Any idea how to solve it?

This is my AppCode and plugin version:

AppCode 2018.2.5
Build #OC-182.5107.23, built on November 13, 2018
JRE: 1.8.0_152-release-1248-b22 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.1
SwiftLint version 0.28.2
SwiftLint plugin version 1.10.3

The problem is not easy to reproduce I guess, as you are familiar with AppCode or JetBrains IDE's, they have an event log in the bottom right part of the window, and there I keep getting this error every time I'm typing or just navigating through the file. And this happens with every file, even if it is short.

When SwiftLint runs at build time, I get the Linting messages and get warnings with no problems, it looks like it is a problem with the AppCode plugin that runs in the background analyzing the files in real time.

Thanks.

**Comment by Antowkos** [comment]
@yeswolf, @bealex, hi guys! It seems like you've fixed this issue. Do you plan to release this version? Or maybe I can build it from master branch?

**Comment by bealex** [comment]
Yes, this should be fixed (and I'm very fast with commenting) :-)
