### ISSUE TITLE
CLion support

### ISSUE THREAD

**Issue by Obbut** [bealex/SwiftLintAppCode#39]
For SSS (Server Side Swift) development, it would be great to have CLion support in this plugin. CLion has support for Swift using the Swift plugin from Jetbrains, which is based on AppCode.

**Comment by bealex** [comment]
Hi,
Can you please check the latest version? I tried to open CLion support, but have no easy way of testing it under linux. macOS looks OK

**Comment by bealex** [comment]
@Obbut And can you please try once more?
