### ISSUE TITLE
Warning levels do not honor setting

### ISSUE THREAD

**Issue by reitzig** [bealex/SwiftLintAppCode#41]
Despite setting the SwiftLine inspection(s) to level weak warning, they show up as warnings and errors.

![Screenshot 2019-05-02 at 13 14 31](https://user-images.githubusercontent.com/4246780/57072735-ff1ad980-6cde-11e9-823a-24b904d1d1e6.png)
![Screenshot 2019-05-02 at 13 14 56](https://user-images.githubusercontent.com/4246780/57072736-ff1ad980-6cde-11e9-85b9-b3fd3f0ce477.png)
![Screenshot 2019-05-02 at 13 15 28](https://user-images.githubusercontent.com/4246780/57072737-ffb37000-6cde-11e9-8bf4-63d8992f6878.png)

This is with SwiftLint plugin 1.10.5 and AppCode 2019.1.1.

**Comment by bealex** [comment]
That is correct. Highlighting uses SwiftLint settings (in .swiftlint.yml or global), not this line.

**Comment by reitzig** [comment]
Then you might as well remove this entry, it's highly misleading.

Editing the YML from AppCode (disable or reconfigure rule) would be cool, but I guess that's a separate request.

**Comment by bealex** [comment]
Correct. This is absolutely different story and I don't think it will ever be practical to do.
