### ISSUE TITLE
1.10.6 not compatible with AppCode 2020.1 EAP

### ISSUE THREAD

**Issue by MontakOleg** [bealex/SwiftLintAppCode#46]
@bealex, hello!

Just curious why latest plugin version not compatible with latest AppCode.

<img width="946" alt="image" src="https://user-images.githubusercontent.com/1800899/75445357-5547c000-5976-11ea-97dc-354bb38b43e3.png">

<img width="1049" alt="image" src="https://user-images.githubusercontent.com/1800899/75445394-61338200-5976-11ea-94e3-0e427a3aab75.png">

**Comment by bealex** [comment]
That looks like a bug there. It is supported everywhere, including current EAP.

I’ll check that with JB guys.

Thanks!

**Comment by bealex** [comment]
Talked to JB about this problem. They have to deal with it.
