### ISSUE TITLE
Nested swiftlint configuration ignored by AppCode plugin

### ISSUE THREAD

**Issue by AleMaMi** [bealex/SwiftLintAppCode#47]
[SwiftlintPluginExample.zip](https://github.com/bealex/SwiftLintAppCode/files/4517222/SwiftlintPluginExample.zip)

AppCode 2020.1 (Build OC-201.6668.159)
Swiftlint plugin 1.10.6
swiftlint 0.39.2

Turn on AppCode Swiftlint plugin inspections.

   The example shows situation there is nested `.swiftlint.yml` configuration in sub-folder to disable locally specific rule. Running build executes `swiftlint` tool as a step and properly shows one warning, because file in root folder contains issue and rule is enabled (in file `ToggleBoolEnabled.swift`). Same result if `swiftlint` runs from command line (from root of project). But AppCode inspection (real-time) shows warning in the second file (`nested/ToggleBoolDisabled.swift`) as well even this is disabled by local configuration.

   Is there any way how to properly configure this behaviour, or is it a bug?

**Comment by bealex** [comment]
Hi, thanks for the report. Plugin does not support nested configuration files. Guess this is the point of upgrading in the future.

**Comment by fowlerwill** [comment]
Would love this since we've got a specific swiftlint.yml for our tests

**Comment by bealex** [comment]
v 1.11.0 should have this ability
