### ISSUE TITLE
SwiftLint not following .swiftlint.yml (XCode 12.0.1, macOS 11, AppCode 2020.2.3)

### ISSUE THREAD

**Issue by uxduck** [bealex/SwiftLintAppCode#50]
AppCode + SwiftLint plugin (this repo) doesn't do anything, as no warnings are being shown in the IDE. The build process does still generate the warnings, as this is configured as a build phase through xcode.

I am running the latest AppCode 
```
AppCode 2020.2.3
Build #OC-202.7319.70, built on September 16, 2020
Runtime version: 11.0.8+10-b944.31 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 10.16
GC: ParNew, ConcurrentMarkSweep
Memory: 2487M
Cores: 16
Registry: max.suggested.heap.size=8192, ide.balloon.shadow.size=0
Non-Bundled Plugins: com.appcodeplugins.swiftlint
```

with the latest plugin:
1.11.0

and XCode Version 12.0.1 (12A7300)

I tried plugin configured to both 
`/usr/local/Cellar/swiftlint/0.40.3/bin/swiftlint`
and `/usr/local/bin/swiftlint`

I also have a .swiftlint.yml file and enabled the code inspection in preferences > editor > inspections

Please let me know if you need anymore information, as I would love to use this plugin

AppCode warns me about not supporting macOS 10.16, even though I am running macOS 11.

**Comment by uxduck** [comment]
I also have a question regarding `SwiftLintService/`. What is it for? It was not in the original (2nd commit in master)

**Comment by bealex** [comment]
Hi, @ben-xD 

Did you check that inspection is enabled? It is disabled by default.

Usually plugin launches external command line utility. `SwiftLintService` has code that tried to use SwiftLint as internal framework. That solution was much, much slower than current and I left it on the side.

**Comment by uxduck** [comment]
Hi @bealex  :)

Yes, I did enable as shown in screenshot, but it warnings do not show in the editor. I am able to successfully run it when i click `Code > Inspect Code...`
![Screenshot 2020-10-08 at 18 31 47](https://user-images.githubusercontent.com/24711048/95493610-98e6bb80-0994-11eb-915e-fa38d279d16a.png)

**Comment by bealex** [comment]
Is indexing finished? SwiftLint is low priority task and it is run after all other inspections.

**Comment by uxduck** [comment]
Oh, I was only testing one specific linter rule (opt in, `unowned_variable_capture`), and it still doesn't seem to work. However, a swiftlint rule i disabled (`line_length`), is showing up in editor. So it seems like Swiftlint is active, but not following the project root `.swiftlint.yml` file.

Previously, I was not sure how to check for indexing 😃 on AppCode, but I believe it is just should be in the background tasks window. This window is empty.

**Comment by bealex** [comment]
Yup, indexing is somewhere there. And a "checkmark" in upper right corner must be non-opaque green.

I've seen couple of times same behavior, when plugin could not find config file. It's a rare bug I cannot catch for now. Will look into it. You can reopen project or restart AppCode, that should help.

**Comment by uxduck** [comment]
Alright thanks. I have a better understanding of how things work now. I've tried to reopen project and restart AppCode, but I still have the same problem. I was curious how to debug a running plugin? I can try to find out why this problem exists, if its possible.

**Comment by alexfedosov** [comment]
Had exactly the same issue, moving files to another directory in the Project window [cmd+1] helped

**Comment by bealex** [comment]
@alexfedosov Maybe it is possible to show me your directory structure, when this happened? If I can reproduce it, it should be an easy fix.

**Comment by MontakOleg** [comment]
>I was curious how to debug a running plugin?

@ben-xD you can debug plugin by running them from IntelliJ IDEA. 

1. Create plugin debug configuration
<img width="1075" alt="image" src="https://user-images.githubusercontent.com/1800899/96582044-67021d00-12e3-11eb-9f9e-65eaca003010.png">

2. Click "Debug"
<img width="366" alt="image" src="https://user-images.githubusercontent.com/1800899/96582080-76816600-12e3-11eb-8031-5a182398c54e.png">

New AppCode instance will be launched with plugin installed. Then you can add breakpoints etc.

Docs:
https://jetbrains.org/intellij/sdk/docs/basics/getting_started/running_and_debugging_a_plugin.html

**Comment by bealex** [comment]
Please check after updating to 1.13 (update should be available after JB review)

**Comment by topeerz** [comment]
Hi! This still doesn't seem to work - AppCode 2021.1, SwiftLint 1.13.1. Internal rules seems to work when I check "Disable when no .swiftlint.yml present" no warnings are shown. Command line seems to work.

**Comment by bealex** [comment]
@topeerz Can you please send relative (to project root) paths of .swiftlint.yml, its contents and relative path of the file you are trying to process?

Thanks!

**Comment by topeerz** [comment]
My actual project has a bit complicated structure something like:

```
 folder1
   repo1
     main_project
       mp.xcworkspace
       mp.xcodeproj
     
     sub_project1
     sub_project2
   
   repo2
     sub_project3
 
   repo3
     sub_project4
```

I tried putting .swiftlint.uml in folder1, repo1 or main_project.

Since this is a bit complicated and vague I tried this on some older repo I have cloned (with similar result) https://github.com/Clean-Swift/CleanStore 

The code->inspect worked, and inspections are shown in-line for items found via code inspect - yet "regular" swiftlint warnings are not shown. As soon as I uncheck "Disable when no .swiftlint.uml present" I am seeing build-in warnings.

I tried placing .swiftlint.yml in CleanStore-master as well as in it's subfolder CleanStore-master/CleanStore.

**Comment by bealex** [comment]
I've opened CleanStore and checked these cases (version 1.13.2 of the plugin):
0.1. You should check that inspection is turned on. This works in 1.13.2 finally :) (it was always on previously).
0.2. You should wait till all indexing processes are finished, SwiftLint will not start till then.

1. Just default configuration. SwiftLint works with default rules, SwiftLint starts in project directory (`.../CleanStore`)
2. Tick "Disable when no .swiftlint.yml present". Highlighting removed.
3. Put `.swiftlint.yml` in project directory (`.../CleanStore`). Unfortunately, for it to start working you should make a change in current file. After that, `.swiftlint.yml` rules are used.

So except manual starting of the linting process at step 3 (will try to fix it now), it looks like its working.

**Comment by bealex** [comment]
Sent 1.13.3 update that will catch .swiftlint.yml file addings/removals.
