### ISSUE TITLE
Can't disable SwiftLint inspection

### ISSUE THREAD

**Issue by TatyanaShabaeva** [bealex/SwiftLintAppCode#54]
AppCode 2020.3.4 (same with 2021.1 RC)
SwiftLint plugin 1.13.1
swiftlint version 0.43.1

- install SwiftLint plugin, make sure that inspection is disabled in Editor | Inspections | Swift | SwiftLint
- open some file in editor that would trigger SwiftLint errors/warnings -> all errors and warnings are highlighted even though inspection is disabled

<img width="1234" alt="img" src="https://user-images.githubusercontent.com/6057640/116120647-6dc18080-a6c8-11eb-9ebb-35066c526acb.png">

**Comment by bealex** [comment]
@TatyanaShabaeva I think I managed to fix that in 1.13.2. Thanks for noticing!

**Comment by TatyanaShabaeva** [comment]
@bealex Works, thanks!

**Comment by bealex** [comment]
Awesome!
