### ISSUE TITLE
Swiftlint inspections stop working if loaded gradle project

### ISSUE THREAD

**Issue by AleMaMi** [bealex/SwiftLintAppCode#57]
If gradle build configuration is loaded by AppCode to regular Xcode project, Swiftlint plugin inspections stop working.

Steps to reproduce:

0. Prerequisites: Swiftlint plugin installed in AppCode
1. Open attached project (very simple command line project) in AppCode
2. Do not load gradle project (AppCode shows popup about it)
3. Switch on Swiftlint inspections
- There are 2 Issues in `main.swift` - unwrapped optional (configured by `.swiftlint.yml`) and redundant return
4. Load gradle project (no tasks, just empty one)
- Swiftlint issue disappear, only regular Swift inspections are working

Environment:
MacMini (M1, 2020)
macOS: 12.0.1
Xcode: 13.1 (13A1030d)
AppCode: 2021.2.4 (OC-212.5457.65)
Swiftlint plugin: 1.13.4
Swiftlint: 0.45.0

[SwiftlintAndGradle.zip](https://github.com/bealex/SwiftLintAppCode/files/7507939/SwiftlintAndGradle.zip)

**Comment by bealex** [comment]
@AleMaMi Can you please check upcoming version 1.13.5? There are some stability fixes that should help in your case too.

Please reopen the issue if it reproduces.

**Comment by AleMaMi** [comment]
It is still reproducible with macOS 12.2, Xcode 13.2.1, AppCode 2021.3.2, plugin 1.13.5, Swiftlint 0.46.2, gradle 7.3.3.
I cannot re-open this issue, perhaps I have no permissions (or I do not know how).

**Comment by bealex** [comment]
@AleMaMi OK. Problem (or not) is that Gradle project requires you to set directory types manually. If you set `SwiftlintAndGradle` directory as `Project Sources and Headers`, SwiftLint plugin will work there. It does not work on non-source files. Don't know if it is bad or not, but for now it is like this.

And please remember to turn on inspection itself.

**Comment by AleMaMi** [comment]
It makes sense, I will see how it works for bigger project than for the test example. Thanks a lot!
