### ISSUE TITLE
Swiftlint's warnings are visible but autocorrect command does nothing 

### ISSUE THREAD

**Issue by Yurlagin** [bealex/SwiftLintAppCode#58]
<img width="254" alt="Screenshot 2022-02-04 at 06 24 27" src="https://user-images.githubusercontent.com/24584890/152446017-d6078bfb-63b5-4234-9fdc-e7de0622500e.png">

i.e. line_length parameter is set to 140. Should I expect autocorrect command to insert line break?

**Comment by bealex** [comment]
Thanks for the report!

Not all warnings have auto-fixes. line_length does not https://realm.github.io/SwiftLint/line_length.html

You can find if specific warning has an auto-fix in the rule documentation: https://realm.github.io/SwiftLint/rule-directory.html
