### ISSUE TITLE
Excluded files with a wildcard does not work

### ISSUE THREAD

**Issue by AkisArou** [bealex/SwiftLintAppCode#62]
e.g. - Source/*/ExcludedFile.swift
When running swiftlint in command line it works as expected, but AppCode does not respect it.

**Comment by bealex** [comment]
Thanks for the report! Can you describe your configuration/project structure, that is related to it? Thanks!

**Comment by AkisArou** [comment]
Sure! 
The expected excluded files are expressed as: __Packages/*/Package.swift__
```
My iOS App/
├─ My iOS App/
│  ├─ ContentView.swift
├─ Packages/
│  ├─ Package1/
│  │  ├─ Package.swift
│  ├─ Package2/
│  │  ├─ Package.swift
```

**Comment by bealex** [comment]
Thanks! Can you tell where the .swiftlint.yml is placed?

**Comment by AkisArou** [comment]
It is in the root folder of the project

**Comment by bealex** [comment]
Thanks! Will look into it.

**Comment by AkisArou** [comment]
Thank you!

**Comment by bealex** [comment]
Looks like it is a bug in SwiftLint. Here's the link I found: https://github.com/realm/SwiftLint/pull/3534. My plugin lints files one-by-one and in this case SwiftLint does not process excluded directories correctly.
