### ISSUE TITLE
Unfriendly error message when SwiftLint path is misconfigured

### ISSUE THREAD

**Issue by TatyanaShabaeva** [bealex/SwiftLintAppCode#9]
When path to SwiftLint in AppCode preferences is incorrect, every attempt to modify Swift code produces the following error message: "Error: IOException: Cannot run program "/someInvalidPath": error=2, No such file or directory". There is no indication that error is related to SwiftLint plugin.

<img width="1229" alt="invalid_path" src="https://cloud.githubusercontent.com/assets/6057640/22110239/070dfc8e-de6c-11e6-9b38-9262df4e86e7.png">

**Comment by bealex** [comment]
Thanks! Should be fixed in 1.6

**Comment by TatyanaShabaeva** [comment]
Thanks. Checked with v1.6, works.
